# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b5542d3f761a487824b494a7a9df9054f61f80e6d5ad808e28accb15604c14fecbbfe763d4c880de4b3b7715b2efaf9fcdeb64979720d4383f7ec8fd391e1cd

test:
  secret_key_base: fe2403ca60468354331f083e28c83d87496cb64c65c5046e20c76e22804009ab5a5dfd8251939da14fb0492f7e212d81edf61c3a427ff3d6ecf30f90fd1b5ef8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
